### ISSUE TITLE
How to pool univariate/descriptive statistics across imputations?

### ISSUE THREAD

**Issue by hanneoberman** [gerkovink/shinyMice#21]
I want to get a univariate measure of bias to compare to the univariate convergence diagnostics. 

If I understand correctly, the variable means are easy: stack the imputed datasets, and take the average (according to FIMD par 5.1.3 "While the estimated regression coefficients are unbiased, we cannot trust the standard errors,..."). So I thought I needed a different strategy for the standard deviations/variances of the completed variables.  But this thread suggests otherwise: "If you just want to report the descriptive SD of a variable, you can just take the average of the within imputation SDs." (https://lists.gking.harvard.edu/pipermail/amelia/2016-July/001249.html).

I'll ask on Monday in the MICE meeting.

**Comment by stefvanbuuren** [comment]
There’s a difference between a standard error (SE) and an standard deviation (SD).

The SE is an auxiliary statistic of some parameter were interested in, and that we need for testing, confidence intervals, and so on. It varies with sample size, and it is generally not something of scientific interest itself. In multiple imputation, we cannot just average the individidual SE’s (as there would be no between imputation uncertainty).

The SD is a measure of variability, and can be of scientific interest, e.g., the spread of heights round the mean. Pooling to would just follow the normal rules that we use for means and regression weights, as long as they are reasonably normally distributed. For that, we’ll need that the variance estimate of the SD.

Trust this is helpful.

Van: Hanne <notifications@github.com>
Beantwoorden - Aan: gerkovink/shinyMice <reply@reply.github.com>
Datum: donderdag 27 februari 2020 om 19:12
Aan: gerkovink/shinyMice <shinyMice@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [gerkovink/shinyMice] How to pool univariate/descriptive statistics across imputations? (#21)


I want to get a univariate measure of bias to compare to the univariate convergence diagnostics.

If I understand correctly, the variable means are easy: stack the imputed datasets, and take the average (according to FIMD par 5.1.3 "While the estimated regression coefficients are unbiased, we cannot trust the standard errors,..."). So I thought I needed a different strategy for the standard deviations/variances of the completed variables. But this thread suggests otherwise: "If you just want to report the descriptive SD of a variable, you can just take the average of the within imputation SDs." (https://lists.gking.harvard.edu/pipermail/amelia/2016-July/001249.html).

I'll ask on Monday in the MICE meeting.
